
services:
  mongodb:
    image: mongo:latest
    container_name: local-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: open-sesame
    volumes:
      - mongo_data:/data/db
      - ./data:/data/local

volumes:
  mongo_data:


